<?php

namespace Lic\EcommerceBundle\Repository;

/**
 * PanierRepository
 *
 * This class was generated by me. Add your own custom
 * repository methods below.
 */
class PanierRepository extends \Doctrine\ORM\EntityRepository
{
}
